version: '3'
services:
  db:
    image: supabase/postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./sql/walrus--0.1.sql:/docker-entrypoint-initdb.d/walrus--0.1.sql
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
